### ISSUE TITLE
Evaluation - Run Baseline algos using Surprise

### ISSUE THREAD

**Issue by nickgreenquist** [dorukkilitcioglu/books2rec#16]

**Comment by nickgreenquist** [comment]
completed, KNN algos could not be used

**Comment by dorukkilitcioglu** [comment]
One way of circumventing that is to use an approximate nearest neighbors algorithm like [Annoy](https://github.com/spotify/annoy) and [HNSW](https://github.com/nmslib/nmslib). Right now we don't feel like its going to change anything, plus the approximation would raise the error, so this issue will remain closed.
