### ISSUE TITLE
Enquiry about Liveness

### ISSUE THREAD

**Issue by nidhibudhraja** [dorukkilitcioglu/books2rec#31]
Heyy ! I have a team of 6 developers, wanting to contribute to an open source project. We find this very interesting and are willing to contribute to it. Just wanted to enquire are you accepting solutions for the project and also whether you have any new open sub problem statement to be taken up as a project.
Thanking you!
Looking for a response!  
Hoping to work on this !

**Comment by nickgreenquist** [comment]
Neither Doruk or I have time to work on this, but feel free to fork it and expand on it!

Not sure how long Goodreads will support its dataset. They plan to deactivate some APIs which might turn off features like getting recommendations based on the Goodreads profile name.
